package scaffold.common.pdf

object PdfUtils {

  def generateSamplePdf(title: String): Unit = {
    val instructions = List(
      Instruction.PageSize(210, 297),
      Instruction.FontSize(24),
      Instruction.Text(20, 40, title),
      Instruction.FontSize(12),
      Instruction.Text(20, 60, "Generated by Tyrian Scaffold"),
      Instruction.Save(s"$title.pdf")
    )
    JsPDF.run(instructions)
  }
}
